"""English seed data: synonyms and utterance templates per vocabulary ID.

The lexicon builder auto-derives the base word from every symbol
(ACTION_REGISTER -> "register"); this file adds everything the symbol
alone cannot give us: synonyms, idioms, question words, pronouns,
modifier words, and the labeled utterance templates used to train
the statistical intent model.
"""

# Synonyms per vocabulary ID. The base word is auto-derived, so only
# additional surface forms belong here. Multi-word phrases are allowed.
SYNONYMS: dict[str, list[str]] = {
    # ---- actions: software / task domain
    "ACT_000001": ["make", "build up", "generate", "produce", "construct", "form", "establish"],
    "ACT_000002": ["erase", "destroy", "drop", "eliminate", "discard", "scrap"],
    "ACT_000003": ["change", "modify", "set", "alter", "revise", "amend"],
    "ACT_000004": ["assign", "put", "place", "attach", "allocate to"],
    "ACT_000005": ["enroll", "enrol", "sign up", "signup", "inscribe", "admit"],
    "ACT_000006": ["take out", "withdraw", "extract", "expel", "kick out"],
    "ACT_000007": ["relocate", "shift", "displace", "transport"],
    "ACT_000008": ["transmit", "dispatch", "mail", "email", "forward", "ship"],
    "ACT_000009": ["hand", "donate", "grant", "offer", "hand over", "present"],
    "ACT_000010": ["display", "present", "exhibit", "demonstrate"],
    "ACT_000011": ["enumerate", "itemize"],
    "ACT_000012": ["find", "look for", "look up", "seek", "locate", "hunt for", "google"],
    "ACT_000013": ["assist", "aid", "support"],
    "ACT_000014": ["begin", "launch", "initiate", "kick off", "commence"],
    "ACT_000015": ["end", "halt", "terminate", "quit", "cease", "abort"],
    "ACT_000016": ["set up", "setup", "deploy"],
    "ACT_000017": ["unlock", "unfold", "launch"],
    "ACT_000018": ["shut", "shut down", "seal"],
    "ACT_000019": ["peruse", "scan", "skim"],
    "ACT_000020": ["compose", "draft", "type", "jot down", "note down"],
    "ACT_000021": ["store", "persist", "keep", "preserve", "back up", "backup"],
    "ACT_000022": ["fetch", "retrieve", "get", "pull up"],
    "ACT_000023": ["link", "attach", "join to", "plug in", "pair"],
    "ACT_000024": ["unlink", "detach", "unplug", "unpair"],
    "ACT_000025": ["activate", "turn on", "switch on"],
    "ACT_000026": ["deactivate", "turn off", "switch off"],
    "ACT_000027": ["permit", "let", "authorize", "approve"],
    "ACT_000028": ["refuse", "forbid", "disallow", "decline", "prohibit"],
    "ACT_000029": ["ask for", "demand", "solicit", "apply for", "beg"],
    "ACT_000030": ["agree to", "take", "receive", "adopt", "embrace"],
    "ACT_000031": ["decline", "refuse", "turn down", "dismiss", "veto"],
    "ACT_000032": ["abort", "call off", "revoke", "annul", "void"],
    "ACT_000033": ["verify", "affirm", "validate", "certify"],
    "ACT_000034": ["contrast", "differentiate", "weigh against"],
    "ACT_000035": ["order", "arrange", "rank", "organize by"],
    "ACT_000036": ["narrow down", "screen", "sift"],
    "ACT_000037": ["tally", "number", "enumerate"],
    "ACT_000038": ["gauge", "quantify", "size up"],
    "ACT_000039": ["compute", "figure out", "work out", "sum up"],
    "ACT_000040": ["choose", "pick", "opt for", "elect"],
    "ACT_000041": ["duplicate", "replicate", "clone", "reproduce"],
    "ACT_000042": ["combine", "unify", "consolidate", "fuse", "blend"],
    "ACT_000043": ["divide", "separate", "partition", "break up"],
    "ACT_000044": ["bring in", "ingest"],
    "ACT_000045": ["send out"],
    "ACT_000046": ["release", "post", "put out", "issue"],
    "ACT_000047": ["follow", "sign up for", "opt in"],
    "ACT_000048": ["inform", "alert", "tell about", "remind", "ping"],
    "ACT_000049": ["book", "plan for", "arrange", "set a time", "calendar"],
    "ACT_000050": ["book", "hold", "set aside", "earmark"],
    "ACT_000051": ["free", "let go", "unhand"],
    "ACT_000052": ["secure", "bolt", "fasten"],
    "ACT_000053": ["unfasten", "unbolt"],
    "ACT_000054": ["log in", "login", "sign in", "verify identity"],
    "ACT_000055": ["grant access", "clear", "empower"],
    "ACT_000056": ["withdraw", "rescind", "retract", "take back"],
    "ACT_000057": ["purchase", "acquire", "shop for", "order"],
    "ACT_000058": ["vend", "market", "trade", "retail"],
    "ACT_000059": ["settle", "remit", "compensate", "reimburse"],
    "ACT_000060": ["instruct", "tutor", "coach", "educate", "mentor"],
    "ACT_000061": ["study", "master", "pick up", "absorb"],
    "ACT_000062": ["drill", "exercise", "coach"],
    "ACT_000063": ["examine", "assess", "quiz", "try out"],
    "ACT_000064": ["assess", "appraise", "review", "rate", "grade"],
    "ACT_000065": ["advance", "elevate", "upgrade"],
    "ACT_000066": ["move over", "reassign", "shift to"],
    "ACT_000067": ["assign", "apportion", "earmark", "budget"],
    "ACT_000068": ["spread", "hand out", "share out", "disperse", "circulate"],
    "ACT_000069": ["gather", "assemble", "accumulate", "amass", "compile"],
    "ACT_000070": ["construct", "assemble", "erect", "put together"],
    "ACT_000071": ["fix", "mend", "patch", "restore", "service"],
    "ACT_000072": ["examine", "review", "audit", "scrutinize", "look over"],
    "ACT_000073": ["watch", "observe", "track", "keep an eye on", "supervise"],
    "ACT_000074": ["brief", "notify about", "present findings"],
    "ACT_000075": ["record", "note", "register event", "journal"],
    "ACT_000076": ["hold on", "hang on", "stand by", "await"],
    "ACT_000077": ["continue", "carry on", "proceed", "go on", "pick up again"],
    "ACT_000078": ["suspend", "hold", "put on hold", "freeze"],
    "ACT_000079": ["try again", "attempt again", "redo attempt"],
    "ACT_000080": ["revert", "roll back", "reverse", "take back"],
    "ACT_000081": ["restart", "reinitialize", "reboot", "clear"],
    "ACT_000082": ["run", "perform", "carry out", "do", "conduct"],
    "ACT_000083": ["distribute", "divide with", "split with"],
    "ACT_000084": ["conceal", "mask", "cover", "obscure", "bury"],
    "ACT_000085": ["show", "expose", "uncover", "unveil", "disclose"],
    "ACT_000086": ["guard", "shield", "defend", "safeguard", "secure"],
    "ACT_000087": ["convert", "interpret", "render", "localize"],
    "ACT_000088": ["clarify", "describe", "elaborate", "spell out", "walk through"],
    "ACT_000089": ["condense", "recap", "abridge", "shorten", "sum up", "tldr"],
    "ACT_000090": ["classify", "group", "sort into", "bucket"],
    "ACT_000091": ["label", "mark with", "annotate"],
    "ACT_000092": ["flag", "highlight", "star", "bookmark"],
    "ACT_000093": ["store away", "file away", "shelve", "retire"],
    "ACT_000094": ["recover", "bring back", "reinstate", "revive"],
    "ACT_000095": ["ask over", "summon", "call in", "welcome in"],
    "ACT_000096": ["track", "trail", "shadow", "pursue"],
    "ACT_000097": ["go to", "head to", "find the way", "steer"],
    "ACT_000098": ["fetch remote", "pull down", "grab"],
    "ACT_000099": ["push up", "post"],
    "ACT_000100": ["print out", "hard copy"],
    # ---- actions: perception / body / motion
    "ACT_000101": ["talk", "say", "utter", "converse", "chat", "communicate"],
    "ACT_000102": ["pay attention", "tune in", "hearken"],
    "ACT_000103": ["look", "watch", "view", "observe", "glance", "stare", "notice"],
    "ACT_000104": ["overhear", "pick up sound"],
    "ACT_000105": ["feel", "contact", "tap", "press"],
    "ACT_000106": ["sniff", "scent"],
    "ACT_000107": ["sample", "savor"],
    "ACT_000108": ["stroll", "hike", "march", "wander"],
    "ACT_000109": ["sprint", "jog", "dash", "race"],
    "ACT_000110": ["sit down", "be seated", "take a seat"],
    "ACT_000111": ["stand up", "rise", "get up"],
    "ACT_000112": ["nap", "rest", "doze", "snooze"],
    "ACT_000113": ["wake up", "awaken", "get up", "rouse"],
    "ACT_000114": ["consume", "dine", "feast", "snack", "devour"],
    "ACT_000115": ["sip", "gulp", "swallow"],
    "ACT_000116": ["prepare", "bake", "fry", "boil", "roast", "grill"],
    "ACT_000117": ["tidy", "scrub", "sweep", "mop", "dust", "wipe"],
    "ACT_000118": ["rinse", "launder", "bathe", "shower"],
    "ACT_000119": ["put on", "dress in", "don"],
    "ACT_000120": ["have fun", "recreate", "perform"],
    "ACT_000121": ["chant", "hum", "vocalize"],
    "ACT_000122": ["boogie", "sway"],
    "ACT_000123": ["sketch", "illustrate", "paint", "doodle"],
    "ACT_000124": ["steer", "pilot", "operate vehicle", "commute"],
    "ACT_000125": ["soar", "glide", "take off"],
    "ACT_000126": ["dive", "paddle", "float"],
    "ACT_000127": ["scale", "ascend", "mount"],
    "ACT_000128": ["leap", "hop", "bounce", "spring"],
    "ACT_000129": ["toss", "hurl", "pitch", "fling", "cast"],
    "ACT_000130": ["grab", "seize", "intercept", "snag"],
    "ACT_000131": ["shove", "press", "nudge", "thrust"],
    "ACT_000132": ["drag", "tug", "yank", "draw"],
    "ACT_000133": ["raise", "hoist", "elevate", "pick up"],
    "ACT_000134": ["haul", "lug", "bear", "tote"],
    "ACT_000135": ["grip", "grasp", "clutch", "keep"],
    "ACT_000136": ["let fall", "release", "let go of"],
    "ACT_000137": ["slice", "chop", "trim", "carve", "snip", "shear"],
    "ACT_000138": ["blend", "stir", "combine", "whisk"],
    "ACT_000139": ["spill", "decant", "drizzle"],
    "ACT_000140": ["load", "stock", "top up", "refill"],
    "ACT_000141": ["drain", "clear out", "unload", "vacate"],
    "ACT_000142": ["grab", "pick", "obtain", "collect", "acquire"],
    "ACT_000143": ["deliver", "fetch", "carry over", "convey"],
    "ACT_000144": ["give back", "go back", "come back", "restore to"],
    "ACT_000145": ["take on loan", "rent", "hire"],
    "ACT_000146": ["loan", "let borrow", "advance"],
    "ACT_000147": ["swap", "trade", "barter", "switch"],
    "ACT_000148": ["cover", "envelop", "bundle", "package"],
    "ACT_000149": ["box", "bag", "crate", "load up"],
    "ACT_000150": ["unbox", "unload", "unwrap"],
    "ACT_000151": ["phone", "ring", "dial", "call up", "telephone"],
    "ACT_000152": ["respond", "pick up", "reply to"],
    "ACT_000153": ["respond", "write back", "answer back", "get back to"],
    "ACT_000154": ["encounter", "get together", "meet up", "rendezvous", "see"],
    "ACT_000155": ["drop by", "stop by", "call on", "tour", "go see"],
    "ACT_000156": ["wed", "get married", "tie the knot", "espouse"],
    "ACT_000157": ["embrace", "cuddle", "squeeze"],
    "ACT_000158": ["peck", "smooch"],
    "ACT_000159": ["grin", "beam"],
    "ACT_000160": ["giggle", "chuckle", "crack up"],
    "ACT_000161": ["weep", "sob", "tear up", "bawl"],
    "ACT_000162": ["yell", "scream", "holler", "cry out", "bellow"],
    "ACT_000163": ["murmur", "mutter", "speak softly"],
    "ACT_000164": ["inform", "let know", "narrate", "recount", "relay"],
    "ACT_000165": ["declare", "proclaim", "broadcast news", "publicize", "reveal publicly"],
    "ACT_000166": ["pledge", "vow", "swear", "commit", "guarantee"],
    "ACT_000167": ["caution", "alert", "notify of danger", "forewarn"],
    "ACT_000168": ["counsel", "guide", "consult"],
    "ACT_000169": ["propose", "put forward", "float", "pitch"],
    "ACT_000170": ["endorse", "vouch for", "advocate", "commend"],
    "ACT_000171": ["command", "direct", "instruct", "mandate", "decree"],
    "ACT_000172": ["ban", "prohibit", "bar", "outlaw", "disallow"],
    "ACT_000173": ["architect", "draft", "blueprint", "model"],
    "ACT_000174": ["arrange", "schedule out", "map out", "prepare", "strategize"],
    "ACT_000175": ["arrange", "coordinate", "structure", "systematize"],
    "ACT_000176": ["run", "administer", "oversee", "direct", "govern", "handle"],
    "ACT_000177": ["guide", "head", "command", "spearhead", "captain"],
    "ACT_000178": ["comply", "follow orders", "submit", "heed"],
    "ACT_000179": ["cast a ballot", "ballot", "poll"],
    "ACT_000180": ["choose by vote", "vote in", "appoint"],
    "ACT_000181": ["assess", "adjudicate", "arbitrate", "rule on"],
    "ACT_000182": ["penalize", "discipline", "sanction", "fine"],
    "ACT_000183": ["prize", "recompense", "recognize", "honor"],
    "ACT_000184": ["pardon", "excuse", "absolve", "let off"],
    "ACT_000185": ["fault", "accuse", "point fingers", "hold responsible"],
    "ACT_000186": ["applaud", "compliment", "laud", "acclaim", "commend"],
    "ACT_000187": ["fault", "knock", "pan", "denounce", "condemn"],
    "ACT_000188": ["grumble", "whine", "protest", "gripe", "moan"],
    "ACT_000189": ["commemorate", "mark", "fete", "rejoice", "party"],
    "ACT_000190": ["worship", "meditate", "invoke"],
    "ACT_000191": ["review", "revise", "cram", "prepare for exam"],
    "ACT_000192": ["rehearse", "drill", "train on", "work on"],
    "ACT_000193": ["resolve", "figure out", "crack", "work out", "answer"],
    "ACT_000194": ["estimate", "suppose", "speculate", "predict", "bet"],
    "ACT_000195": ["look at", "review", "go over", "double check", "confirm state"],
    "ACT_000196": ["confirm", "validate", "double-check", "corroborate", "fact check"],
    "ACT_000197": ["demonstrate", "establish", "show evidence", "substantiate"],
    "ACT_000198": ["find out", "uncover", "detect", "unearth", "identify"],
    "ACT_000199": ["investigate", "survey", "probe", "scout", "delve into"],
    "ACT_000200": ["journey", "tour", "voyage", "trek", "commute", "go abroad"],
    "ACT_000201": ["flee", "get away", "break free", "run away", "evade"],
    "ACT_000202": ["pursue", "run after", "hunt down", "tail"],
    "ACT_000203": ["stalk", "trap", "poach", "track down"],
    "ACT_000204": ["battle", "combat", "struggle", "brawl", "wrestle"],
    "ACT_000205": ["assault", "strike", "raid", "charge", "ambush"],
    "ACT_000206": ["guard", "shield", "protect from", "ward off", "repel"],
    "ACT_000207": ["triumph", "prevail", "come first", "beat"],
    "ACT_000208": ["be defeated", "misplace", "forfeit", "drop"],
    "ACT_000209": ["contend", "vie", "race against", "rival"],
    "ACT_000210": ["hurt", "injure", "damage", "wound", "abuse"],
    "ACT_000211": ["cure", "recover", "mend", "restore health"],
    "ACT_000212": ["medicate", "care for", "nurse", "attend to"],
    "ACT_000213": ["identify illness", "assess condition", "screen"],
    "ACT_000214": ["sow", "seed", "cultivate", "transplant"],
    "ACT_000215": ["reap", "gather crops", "pick crops"],
    "ACT_000216": ["nourish", "give food", "nurse"],
    "ACT_000217": ["mount", "cycle", "bike"],
    "ACT_000218": ["capture", "tape", "film", "videotape"],
    "ACT_000219": ["air", "transmit", "stream", "televise"],
    "ACT_000220": ["revise", "modify text", "proofread", "rewrite", "polish"],
    # ---- states
    "STA_000001": ["exist as", "am", "are", "is", "was", "were", "been"],
    "STA_000002": ["possess", "hold", "own", "carry", "got"],
    "STA_000003": ["be aware", "be familiar with", "recognize", "recall"],
    "STA_000004": ["desire", "wish for", "crave", "long for", "would like", "fancy"],
    "STA_000005": ["require", "must have", "lack", "demand"],
    "STA_000006": ["enjoy", "be fond of", "appreciate", "favor", "fancy"],
    "STA_000007": ["favor", "would rather", "lean toward", "choose over"],
    "STA_000008": ["trust that", "be convinced", "hold that", "have faith"],
    "STA_000009": ["believe", "consider", "reckon", "suppose", "figure", "assume", "reflect"],
    "STA_000010": ["sense", "experience", "perceive"],
    "STA_000011": ["wish", "aspire", "look forward", "long"],
    "STA_000012": ["anticipate", "await", "foresee", "count on"],
    "STA_000013": ["be afraid", "dread", "be scared", "worry about", "panic"],
    "STA_000014": ["rely on", "have confidence in", "count on", "believe in"],
    "STA_000015": ["question", "be unsure", "suspect", "distrust"],
    "STA_000016": ["comprehend", "grasp", "get", "follow", "make sense of"],
    "STA_000017": ["recall", "recollect", "keep in mind", "memorize"],
    "STA_000018": ["not remember", "lose track", "blank on"],
    "STA_000019": ["possess", "hold title", "be owner"],
    "STA_000020": ["be part of", "be member of", "pertain to"],
    "STA_000021": ["hold", "include", "house", "encompass", "comprise"],
    "STA_000022": ["be", "be real", "be present", "occur"],
    "STA_000023": ["be missing", "be short of", "be without", "want for"],
    "STA_000024": ["need", "call for", "demand", "necessitate"],
    "STA_000025": ["rely", "hinge on", "rest on", "be contingent"],
    "STA_000026": ["adore", "cherish", "be in love with", "treasure", "be devoted to"],
    "STA_000027": ["despise", "detest", "loathe", "abhor", "cannot stand"],
    "STA_000028": ["relish", "delight in", "take pleasure", "savor", "appreciate"],
    "STA_000029": ["long for", "yearn for", "pine for", "feel absence"],
    "STA_000030": ["mind", "be concerned", "look after", "worry about"],
    "STA_000031": ["hope for", "dream of", "want badly", "if only"],
    "STA_000032": ["be sorry about", "rue", "lament", "feel bad about"],
    "STA_000033": ["appear", "look", "come across as", "sound like"],
    "STA_000034": ["look like", "take after", "be similar to", "mirror"],
    "STA_000035": ["correspond", "align with", "fit with", "go with"],
    "STA_000036": ["vary", "diverge", "be unlike", "contrast with"],
    "STA_000037": ["be the same as", "amount to", "be identical to"],
    "STA_000038": ["be priced at", "run", "set back", "amount to"],
    "STA_000039": ["have weight", "tip the scales"],
    "STA_000040": ["signify", "denote", "stand for", "imply", "indicate"],
    "STA_000041": ["be important", "count", "be significant", "weigh"],
    "STA_000042": ["suit", "be right for", "conform to", "go in"],
    "STA_000043": ["merit", "be worthy", "earn", "warrant"],
    "STA_000044": ["contain", "cover", "encompass", "take in"],
    "STA_000045": ["leave out", "omit", "rule out", "bar"],
    "STA_000046": ["be made of", "comprise", "be composed"],
    "STA_000047": ["stay", "keep being", "continue as", "persist"],
    "STA_000048": ["reside", "dwell", "inhabit", "stay at", "be based in"],
    "STA_000049": ["be employed", "function", "operate", "serve", "have a job"],
    "STA_000050": ["endure", "undergo", "go through", "be afflicted"],
    "STA_000051": ["ache", "be in pain", "sting", "throb"],
    "STA_000052": ["be indebted", "be liable for", "have debt"],
    "STA_000053": ["stand for", "symbolize", "act for", "speak for"],
    "STA_000054": ["back", "uphold", "stand behind", "side with", "endorse"],
    "STA_000055": ["be against", "resist", "object to", "stand against"],
    "STA_000056": ["stop from", "block", "avert", "hinder", "deter"],
    "STA_000057": ["bring about", "lead to", "result in", "trigger", "produce"],
    "STA_000058": ["mean to", "aim to", "plan to", "purpose"],
    "STA_000059": ["prize", "treasure", "hold dear", "esteem"],
    "STA_000060": ["esteem", "honor", "look up to", "revere", "admire"],
    # ---- queries (question words and constructions)
    "QRY_000001": ["do you know", "are you familiar", "have you heard of"],
    "QRY_000002": ["question", "inquire", "wonder"],
    "QRY_000003": ["what", "what is", "what are", "whats"],
    "QRY_000004": ["who", "who is", "who are", "whos"],
    "QRY_000005": ["where", "where is", "where are", "wheres"],
    "QRY_000006": ["when", "when is", "what time"],
    "QRY_000007": ["why", "how come", "for what reason", "whats the reason"],
    "QRY_000008": ["how", "how do", "how does", "in what way", "by what means"],
    "QRY_000009": ["which", "which one", "which of"],
    "QRY_000010": ["whether", "if"],
    "QRY_000011": ["how many"],
    "QRY_000012": ["how much"],
    "QRY_000013": ["can you", "could you", "are you able", "is it possible"],
    "QRY_000014": ["should", "ought", "is it wise"],
    "QRY_000015": ["may i", "am i allowed", "is it okay to"],
    "QRY_000016": ["must", "do i have to", "is it required"],
    "QRY_000017": ["will", "shall", "is going to"],
    "QRY_000018": ["did", "has", "have you", "was there"],
    "QRY_000019": ["is there", "are there", "does there exist", "any"],
    "QRY_000020": ["how is", "hows", "what is the status", "what state"],
    "QRY_000021": ["what do you think", "whats your opinion", "how do you see"],
    "QRY_000022": ["which do you prefer", "what would you rather", "favorite"],
    "QRY_000023": ["who are you", "what are you", "introduce yourself"],
    "QRY_000024": ["right", "correct", "isnt it", "no", "yeah"],
    "QRY_000025": ["or", "either or", "which one of"],
    "QRY_000026": ["what does mean", "define", "what is the meaning", "meaning of"],
    "QRY_000027": ["how long", "for how long", "what duration"],
    "QRY_000028": ["how far", "what distance"],
    "QRY_000029": ["how often", "how frequently", "how many times"],
    "QRY_000030": ["whose", "who owns", "belonging to whom"],
    # ---- events
    "EVT_000001": ["join", "enter", "become member", "come aboard"],
    "EVT_000002": ["leave", "exit", "quit", "walk out", "withdraw from"],
    "EVT_000003": ["arrive", "get there", "reach", "show up", "turn up", "land"],
    "EVT_000004": ["depart", "set off", "head out", "take off", "leave for"],
    "EVT_000005": ["complete", "finish", "wrap up", "conclude", "get done"],
    "EVT_000006": ["begin", "start", "commence", "get underway"],
    "EVT_000007": ["end", "finish", "conclude", "come to an end", "wind down"],
    "EVT_000008": ["occur", "happen", "take place", "come about", "transpire"],
    "EVT_000009": ["change", "transform", "turn into", "become", "shift"],
    "EVT_000010": ["increase", "grow", "rise", "climb", "go up", "surge", "expand"],
    "EVT_000011": ["decrease", "drop", "fall", "decline", "shrink", "go down", "dip"],
    "EVT_000012": ["succeed", "work out", "pan out", "come through", "make it"],
    "EVT_000013": ["fail", "flop", "fall through", "go wrong", "not work"],
    "EVT_000014": ["expire", "run out", "lapse", "time out"],
    "EVT_000015": ["break", "break down", "malfunction", "stop working", "give out"],
    "EVT_000016": ["be born", "birth", "come into the world"],
    "EVT_000017": ["die", "pass away", "pass on", "perish"],
    "EVT_000018": ["meeting", "gathering", "assembly", "session"],
    "EVT_000019": ["fall", "tumble", "collapse", "drop down", "topple"],
    "EVT_000020": ["rise", "go up", "ascend", "lift"],
    "EVT_000021": ["crash", "collide", "smash", "wreck"],
    "EVT_000022": ["error", "fault", "bug", "failure", "glitch", "exception"],
    "EVT_000023": ["timeout", "time out", "deadline passed"],
    "EVT_000024": ["log in", "login", "sign in", "signed in"],
    "EVT_000025": ["log out", "logout", "sign out", "signed out"],
    "EVT_000026": ["delivery", "arrived package", "shipment came"],
    "EVT_000027": ["launch", "release", "go live", "rollout", "debut"],
    "EVT_000028": ["shutdown", "shut down", "power off", "outage"],
    "EVT_000029": ["upgrade", "level up", "version up"],
    "EVT_000030": ["downgrade", "roll back version"],
    "EVT_000031": ["rain", "raining", "rained", "drizzle", "shower"],
    "EVT_000032": ["snow", "snowing", "snowed"],
    "EVT_000033": ["storm", "thunderstorm", "hurricane", "cyclone"],
    "EVT_000034": ["fire", "blaze", "burning"],
    "EVT_000035": ["flood", "flooding", "overflow"],
    "EVT_000036": ["accident", "crash", "mishap", "incident"],
    "EVT_000037": ["graduation", "graduate", "graduated"],
    "EVT_000038": ["wedding", "marriage ceremony"],
    "EVT_000039": ["party", "celebration", "get together", "bash"],
    "EVT_000040": ["holiday", "vacation", "day off", "break"],
    # ---- modifiers (function words)
    "MOD_000001": ["not", "never", "no", "dont", "doesnt", "didnt", "wont", "cant", "isnt", "arent", "without"],
    "MOD_000002": ["maybe", "possibly", "might", "perhaps", "could be", "potentially"],
    "MOD_000003": ["must", "necessarily", "have to", "has to", "need to"],
    "MOD_000004": ["should", "ought to", "supposed to", "had better"],
    "MOD_000005": ["may", "allowed to", "permitted to"],
    "MOD_000006": ["can", "able to", "capable of", "know how to"],
    "MOD_000007": ["very", "extremely", "slightly", "quite", "so", "too", "really"],
    "MOD_000008": ["always", "sometimes", "rarely", "often", "usually", "never", "occasionally", "daily", "weekly"],
    "MOD_000009": ["briefly", "permanently", "for a while", "temporarily", "forever"],
    "MOD_000010": ["completely", "partially", "fully", "half", "entirely", "almost done"],
    "MOD_000011": ["if", "unless", "provided that", "in case", "as long as"],
    "MOD_000012": ["in order to", "so that", "for the purpose of", "to"],
    "MOD_000013": ["carefully", "quickly", "slowly", "gently", "loudly", "quietly", "well", "badly"],
    "MOD_000014": ["almost", "nearly", "fully", "partly", "barely", "hardly"],
    "MOD_000015": ["definitely", "probably", "certainly", "surely", "likely", "undoubtedly"],
    "MOD_000016": ["please", "kindly", "if you dont mind", "would you mind"],
    "MOD_000017": ["immediately", "urgently", "asap", "right away", "now", "at once", "instantly"],
    "MOD_000018": ["all", "some", "few", "many", "most", "several", "every", "each", "any", "none"],
    "MOD_000019": ["more than", "less than", "bigger than", "smaller than", "as much as"],
    "MOD_000020": ["best", "most", "largest", "worst", "least", "greatest", "smallest"],
    "MOD_000021": ["about", "around", "roughly", "approximately", "nearly", "some"],
    "MOD_000022": ["really", "indeed", "absolutely", "truly", "honestly", "seriously"],
    "MOD_000023": ["yesterday", "ago", "last week", "last year", "before", "previously", "earlier"],
    "MOD_000024": ["now", "currently", "at the moment", "today", "presently"],
    "MOD_000025": ["tomorrow", "soon", "later", "next week", "next year", "eventually", "shortly"],
    "MOD_000026": ["still", "currently doing", "in progress", "ongoing"],
    "MOD_000027": ["already", "just finished", "done", "have done"],
    "MOD_000028": ["every day", "regularly", "habitually", "routinely"],
    "MOD_000029": ["was done", "been done", "got done", "by"],
    "MOD_000030": ["only", "just", "merely", "solely", "exclusively", "nothing but"],
    # ---- meta (conversational)
    "META_000001": ["hello", "hi", "hey", "good morning", "good afternoon", "good evening", "greetings", "howdy", "yo"],
    "META_000002": ["bye", "goodbye", "see you", "see you later", "farewell", "take care", "good night", "catch you later"],
    "META_000003": ["thanks", "thank you", "thanks a lot", "much appreciated", "cheers", "many thanks", "thx"],
    "META_000004": ["sorry", "i apologize", "my apologies", "excuse me", "pardon me", "my bad", "forgive me"],
    "META_000005": ["yes", "yeah", "yep", "correct", "right", "exactly", "sure", "of course", "affirmative", "indeed"],
    "META_000006": ["no", "nope", "nah", "incorrect", "wrong", "not at all", "negative"],
    "META_000007": ["i agree", "agreed", "exactly", "true", "you are right", "fair enough", "good point"],
    "META_000008": ["i disagree", "not quite", "i dont think so", "not really", "i beg to differ"],
    "META_000009": ["ok", "okay", "got it", "understood", "alright", "noted", "roger", "i see", "fine"],
    "META_000010": ["pardon", "what", "sorry what", "come again", "say again", "huh"],
    "META_000011": ["what do you mean", "can you clarify", "im confused", "i dont understand", "meaning"],
    "META_000012": ["i am", "my name is", "this is", "im called", "let me introduce"],
    "META_000013": ["nice work", "well done", "great job", "impressive", "beautiful", "excellent", "amazing", "awesome"],
    "META_000014": ["congratulations", "congrats", "way to go", "bravo"],
    "META_000015": ["welcome", "come in", "make yourself at home", "youre welcome"],
    "META_000016": ["good luck", "safe travels", "all the best", "best wishes", "have a good day", "have fun"],
    "META_000017": ["my condolences", "so sorry for your loss", "deepest sympathy", "rest in peace"],
    "META_000018": ["wow", "oh", "ouch", "oops", "whoa", "yikes", "phew", "hmm", "aha", "omg"],
    "META_000019": ["um", "uh", "well", "er", "hmm", "let me think", "you know"],
    "META_000020": ["by the way", "anyway", "speaking of which", "on another note", "btw", "changing topics"],
    "META_000021": ["hey", "excuse me", "listen", "look", "attention", "hello there", "psst"],
    "META_000022": ["you can do it", "keep going", "dont give up", "hang in there", "go for it", "keep it up"],
    "META_000023": ["it will be okay", "dont worry", "everything will be fine", "there there", "it happens"],
    "META_000024": ["just kidding", "haha", "lol", "thats funny", "im joking"],
    "META_000025": ["how about this weather", "how are you", "hows it going", "whats up", "how have you been", "hows life"],
}

# Pronouns and deictics -> reserved reference IDs.
PRONOUNS: dict[str, str] = {
    "i": "REF_SPEAKER", "me": "REF_SPEAKER", "my": "REF_SPEAKER",
    "mine": "REF_SPEAKER", "myself": "REF_SPEAKER", "we": "REF_SPEAKER",
    "us": "REF_SPEAKER", "our": "REF_SPEAKER", "ours": "REF_SPEAKER",
    "you": "REF_LISTENER", "your": "REF_LISTENER", "yours": "REF_LISTENER",
    "yourself": "REF_LISTENER", "yourselves": "REF_LISTENER",
    "he": "REF_PREVIOUS_ENTITY", "she": "REF_PREVIOUS_ENTITY",
    "him": "REF_PREVIOUS_ENTITY", "her": "REF_PREVIOUS_ENTITY",
    "his": "REF_PREVIOUS_ENTITY", "hers": "REF_PREVIOUS_ENTITY",
    "it": "REF_PREVIOUS_ENTITY", "its": "REF_PREVIOUS_ENTITY",
    "they": "REF_PREVIOUS_ENTITY", "them": "REF_PREVIOUS_ENTITY",
    "their": "REF_PREVIOUS_ENTITY", "theirs": "REF_PREVIOUS_ENTITY",
    "this": "REF_PREVIOUS_ENTITY", "that": "REF_PREVIOUS_ENTITY",
    "these": "REF_PREVIOUS_ENTITY", "those": "REF_PREVIOUS_ENTITY",
    "here": "REF_HERE", "there": "REF_HERE",
    "now": "REF_TIME_NOW", "today": "REF_TIME_NOW", "tonight": "REF_TIME_NOW",
    "yesterday": "REF_TIME_PAST", "tomorrow": "REF_TIME_FUTURE",
}

# Slot fillers for corpus generation.
NAMES = ["clarissa", "alice", "bob", "john", "mary", "peter", "grace", "david", "keza", "eric"]
THINGS = ["the file", "the report", "a document", "the photo", "my account", "the door",
          "the class", "the list", "dinner", "the car", "a message", "the book",
          "the project", "the meeting", "the schedule", "my homework", "the room"]
GROUPS = ["biology a1", "the team", "math class", "the group", "the club", "the system"]

# Utterance templates per vocabulary ID. {verb} is replaced by each synonym,
# {name}/{thing}/{group} by slot fillers. These train the intent classifier.
TEMPLATES: dict[str, list[str]] = {
    "__ACT_DEFAULT__": [
        "{verb} {thing}",
        "please {verb} {thing}",
        "can you {verb} {thing}",
        "{verb} {thing} now",
        "i want to {verb} {thing}",
        "could you {verb} {thing} for me",
    ],
    "__STA_DEFAULT__": [
        "i {verb} {thing}",
        "she {verb} {thing}",
        "we {verb} {thing}",
        "they {verb} it",
        "do you {verb} {thing}",
    ],
    "__EVT_DEFAULT__": [
        "{thing} {verb}",
        "the {verb} happened",
        "there was a {verb}",
        "it {verb} yesterday",
    ],
    "__META_DEFAULT__": [
        "{verb}",
        "{verb} everyone",
        "{verb} my friend",
    ],
    "ACT_000005": [
        "{verb} {name} in {group}",
        "please {verb} {name} in {group}",
        "{verb} {name} into {group}",
        "can you {verb} {name} in {group}",
    ],
    "ACT_000004": [
        "{verb} {name} to {group}",
        "please {verb} {name} to {group}",
    ],
    "ACT_000001": [
        "{verb} a student named {name}",
        "{verb} a class called {group}",
        "please {verb} {thing}",
    ],
    "QRY_000001": [
        "do you know me",
        "do you know her",
        "do you know him",
        "do you know {name}",
        "do you know this",
        "are you familiar with {name}",
        "have you heard of {name}",
    ],
    "QRY_000003": ["what is {thing}", "what is this", "whats that", "what are those"],
    "QRY_000004": ["who is {name}", "who is that", "who are they", "who did this"],
    "QRY_000005": ["where is {name}", "where is {thing}", "where are we", "where am i"],
    "QRY_000006": ["when is {thing}", "when did it happen", "what time is it", "when do we start"],
    "QRY_000007": ["why is {thing} late", "why did she leave", "how come it failed", "why not"],
    "QRY_000008": ["how do i {name}", "how does it work", "how did you do that", "how do we get there"],
    "QRY_000011": ["how many students are there", "how many are left", "how many people came"],
    "QRY_000012": ["how much does it cost", "how much is {thing}", "how much water"],
    "QRY_000013": ["can you help me", "could you do that", "are you able to come", "can she swim"],
    "QRY_000020": ["how is {name}", "hows the project", "what is the status of {thing}"],
    "QRY_000023": ["who are you", "what are you", "tell me about yourself"],
    "QRY_000027": ["how long does it take", "how long is the movie", "for how long"],
    "QRY_000029": ["how often do you run", "how frequently does it happen"],
    "QRY_000030": ["whose book is this", "whose is that", "who owns this car"],
    "STA_000003": ["i know {name}", "she knows him", "we know the answer", "i know that place"],
    "STA_000004": ["i want {thing}", "she wants to go", "we want more time", "i would like {thing}"],
    "STA_000005": [
        "i need {thing}",
        "we need help",
        "she needs a break",
        "you need to rest",
        "i need help with {thing}",
        "i need your help",
        "we need help with this",
    ],
    "META_000014": [
        "congratulations",
        "congrats",
        "congratulations on your {thing}",
        "congratulations on your graduation",
        "congrats on the new job",
        "way to go",
        "bravo",
    ],
    "STA_000026": ["i love you", "i love {thing}", "she loves him", "we love this place"],
    "STA_000001": [
        "{name} is 15 years old",
        "she is a teacher",
        "it is cold",
        "they are students",
        "the sky is blue",
    ],
}
